import { Mark } from "@untitledui/icons";

export const translations = {
  "en-us": {
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    rights: "All rights reserved.",
    hotel: "hotel",
    hotelName: "Sin-kom",
    gallery: "Gallery",
    reservation: "Book now",
    reservationTop: "Booking",
    reception: "Reception",
    parking: "Parking",
    wifi: "Hi-Speed Wi-Fi",
    tv: "Smart TV",
    ac: "Air Conditioning",
    conference: "Conference",
    paragraph1:
      "Garne Sin-Kom Hotel began operating on July 1, 2009. It operates on a bed and breakfast basis and is classified as a 3-star garni hotel by the competent Ministry of the Republic of Serbia.",
    paragraph2:
      "It is located in the most beautiful part of the city, where the oldest shops were once found along the old cobblestone streets. Today, this is a part of the city where, alongside the old architectural core, completely new, modern buildings dominate. Just 200m from the main bus station, in the direction leading to the industrial quarter, and 100m from the turnoff to the Stara Planina Nature Park, Hotel Sin-Kom is built at the crossroads of these routes. Thus, the property is geared both in terms of location and amenities toward business people and guests in transit, as well as lovers of nature and the rich cultural and historical heritage of the Pirot region.",
    paragraph3:
      "The Garni Hotel Sin-Kom also hosts numerous sporting and cultural events and competitions.",
    paragraph4:
      "Every detail of our offering is designed to meet the demands of the modern business world. In addition to our own parking lot, which is under constant video surveillance, the hotel offers the option to organize seminars and conferences. All rooms are comfortable and provide 24-hour internet access.",
    paragraph5:
      "In light of the current global crisis caused by the COVID-19 pandemic, the management of Hotel Sin-Kom has decided to make the upcoming period extra safe, clean, and secure for all our dear Guests. For 12 years, Hotel Sin-Kom has been known as a hotel where cleanliness is our top priority. Today, more than ever, our business principles are coming to the forefront. A safe stay in clean rooms that are maintained to the highest hotel standards and a friendly staff that adheres to all safety measures are now the qualities guests value most.",
    paragraph6:
      "If you're just passing through and want to rest, or if your business trip brings you to Pirot and the surrounding area, come visit us! We will provide you with ideal resting conditions and quality service, and our friendly staff will make your stay pleasant and safe.",
    welcomeMessage: "Welcome!",
    accomodation: "Accomodation and services of our hotel",
    requestACustomQuote: "Request a custom quote",
    conferenceRoom: "Conference Room",
    location: "Location",
    markText: "What our guests say about us",
    servicesOfTheHotel: "Accomodation of hotel",
    servicesDescription: "Explore our hotel's accommodation units, as well as the additional services we offer.",
    conferenceText1:
      "The Sin-Kom Hotel Conference Hall is ideal for all types of seminars, presentations, conferences, promotions, or workshops.",
    conferenceText2:
      "An overview of the optimal seating arrangement (cinema layout), with the option to arrange it as you wish. The maximum capacity of the room is 40 seats.",
    serviceType: "Service type",
    bedAndBreakfast: "Bed and breakfast",
    roomType: "Accommodation type",
    numberOfPersons: "Number of persons",
    onePerson: "One person",
    twoPersons: "Two persons",
    options: "Options",
    extraBed: "Extra bed (1900 RSD)",
    nonSmokingRoom: "Non-smoking room",
    selectPeriod: "Select period",
    addAnotherRoom: "Add another room",
    removeRoom: "Remove room",
    personalData: "Personal details",
    fullName: "Full name",
    mobilePhone: "Mobile phone",
    emailAddress: "Email address",
    address: "Address",
    city: "City",
    country: "Country",
    reservationNotice:
      "Sending a reservation request does not mean that your reservation is confirmed. Our reception will notify you of your reservation confirmation via email as soon as possible.",
    sendRequest: "Send request",
    roomPrice: "Room price",
    clasicRoom: "Classic Room",
    clasicRoomDescription:
      "A comfortable classic room with all the standard amenities for a pleasant stay.",
    comfortRoom: "Comfort Room",
    comfortRoomDescription:
      "Experience extra comfort in this spacious room designed for relaxation.",
    doubleRoom: "Room with a double bed",
    doubleRoomDescription:
      "A spacious double room perfect for couples, featuring a large bed and modern facilities.",
    twoBeds: "Two standard separate beds",
    digiSat: "Digi SAT TV",
    phoneLine: "Direct phone line",
    hairdryer: "Hairdryer",
    sosAlarm: "SOS Alarm",
    priceOnePerson: "B&B for one person",
    priceTwoPersons: "B&B for two persons",
    perNight: "per night",
    airConditioned: "Air conditioned",
    doubleBed: "Double bed",
    hydromassage: "Bathroom with hydromassage cabin",
    hydromassage2: "Hydromassage cabin",
    miniBar: "Mini bar",
    safe: "Safe",
    miniBarNote: "Mini bar (4 out of 6 rooms)",
    conferenceMainText: "Conference room - We offer organization of lectures, conferences, and cocktails.",
    parkingMainText: "Free parking is provided for all guests of our hotel.",
    wirelessInternet: "Hi-Speed Wi-Fi",
    wirelessInternet2: "Hi-Speed Wi-Fi - We provide our guests with unlimited access to high-speed internet.",
    pricing: "Pricing",
    upToHours: "Up to 3 hours",
    perHour: "per hour",
    hotelGuests: "Hotel Guests",
    contactButton: "Contact Us",
    restaurant: "Restaurant",
    restaurantBreakfastInfo: "Guests staying at Hotel Sin-Kom can enjoy a highly-rated breakfast during their stay. Breakfast options include:",
    restaurantBreakfastOption1: "Self-service buffet",
    restaurantBreakfastOption2: "À la carte (ordering from the menu)",
    contactPageSubtitle: "Have a question or want to book a stay? Feel free to reach out to us.",
    messageLabel: "Message",
    messagePlaceholder: "How can we help you?",
    successMessage: "Your message has been sent successfully!",
    errorMessage: "Something went wrong. Please try again.",
    moreHours: "More than 3 hours",
    priceFrom3800: "Price from 3800 RSD",
    priceFrom5000: "Price from 5000 RSD",
    priceFrom4000: "Price from 4000 RSD",
    kinoKonf: "Cinema setup of the conference room",
    konfSto: "Conference table for speakers",
    stoliceTabla: "40 chairs with a writing tablet",
    projektor: "Projector",
    platno: "Projection screen",
    koktelKonf: "Cocktail setup of the conference room",
    razmestajKoktel: "Option to arrange as you wish",
    visokiStolovi: "Setup of high bar tables",
    mainPageText: "Hotel Sin-Kom — Your ideal accommodation in Pirot",
    okolinaTitle: "Discover the surroundings of Pirot",
    zavojskoJezero: "Zavoj Lake",
    zavojskoDescription:
      "Just 15km from the hotel, Zavoj Lake is a picturesque spot perfect for walks and picnics in nature.",
    learnMore: "Learn more",
    staraPlaninaTitle: "Stara Planina",
    staraPlaninaDescription:
      "Stara Planina is a beautiful mountain range perfect for hiking and outdoor activities.",
    vodopadiTitle: "Waterfalls",
    vodopadiDescription:
      "Discover the beautiful waterfalls in the vicinity of Pirot, offering incredible views and opportunities for adventures in nature.",
    okolinaDescription:
      "Explore the natural beauty and attractions around Pirot, from serene lakes to majestic mountains and stunning waterfalls. Whether you're seeking relaxation or adventure, the surroundings of Pirot have something for everyone.",
    reviewTitleFirst: "Desislava (Bulgaria)",
    reviewDescriptionFirst:
      "It is excellent value for the money. The staff were very polite and helpful. The breakfast was very good. It was clean even if the furniture wasn’t new.",
    reviewTitleSecond: "Jonas (Sweden)",
    reviewDescriptionSecond:
      "Really liked this place. Very nice room and good breakfast. Perfect central location near bus station. Very friendly and helpful staff.",
    reviewTitleThird: "Marina (Serbia)",
    reviewDescriptionThird:
      "We stayed at the Sin-Kom hotel for three days, the location of the hotel is great, just a few minutes walk to the center. The room we got is spacious, nice and very clean. The bed is comfortable. The hotel is highly recommended. Thanks to the staff, we had a nice time, we will come back.",
    readReviews: "Read All Reviews",
    surroundings: "Surroundings",
    swiperLine1: "Welcome to Hotel",
    swiperLine2: "to",
    swiperLine3: "Hotel",
    swiperLine4: "Sin-Kom", 
    swiperLine5: "The perfect place for your stay",
    zanimljivostiTitle: "Attractions in Pirot",
    zanimljivostiDescription:
      "Pirot offers a rich cultural experience. Visit the medieval fortress Momčilov grad, explore the Ponišavlja Museum with its authentic architecture, or take a stroll along the most beautiful quay in Serbia by the Nišava River.",
    kaleName: "Kale Fortress",
    muzejName: "Ponišavlja Museum",
    kejName: "Nišava River Quay",
    kaleDesc: "Kale Fortress is a medieval fortress located in the center of Pirot, known for its historical significance and panoramic views of the city.",
    muzejDesc: "Ponišavlja Museum is a cultural institution in Pirot that preserves and exhibits the rich history and tradition of the Ponišavlja region.",
    kejDesc: "Nišava River Quay is a popular place for walking and relaxation along the river, offering beautiful views and a peaceful atmosphere.",
    accomodationButton: "Learn more",
    jermaTitle: "Jerma River Canal",
    jermaDescription: 
      "The Jerma River Canal is a spectacular natural attraction in the vicinity of Pirot, known for its stunning landscapes and opportunities for outdoor activities such as hiking and fishing.",
    poganovoName: "Poganovo Monastery",
    poganovoDesc: 
      "Poganovo Monastery is a Serbian Orthodox monastery located near Pirot, known for its beautiful architecture and serene surroundings, making it a popular destination for visitors interested in history and spirituality.",
    sukovoName: "Sukovo Monastery",
    sukovoDesc: 
      "Sukovo Monastery is a Serbian Orthodox monastery located near Pirot, known for its historical significance and peaceful atmosphere, making it a popular destination for visitors interested in history and spirituality.",
    zvonackaBanjaName: "Zvonačka Banja",
    zvonackaBanjaDesc: 
      "Zvonačka Banja is a well-known spa town near Pirot, famous for the therapeutic properties of its springs and the beautiful natural surroundings.",      
    selectPeriodPlaceholder: "Select your stay period",
      pricingList: "Pricing List",
      bookingBenefits: "Benefits of direct booking",
      bookingBenefit1: "- 10% discount for individual bookings",
      bookingBenefit2: "- Early Check-In and/or Late Check-Out",
      phoneBooking: "Phone Booking",
      konfContact: "Contact us for a personalized offer",
      kozjiKamenName: "Kozji Kamen",
      kozjiKamenDesc: "The Kozji Kamen viewpoint offers a spectacular view of Zavoj Lake and the surrounding mountains.",
      smilovicaName: "Smilovica Viewpoint",
      smilovicaDesc: "The Smilovica viewpoint offers a breathtaking view of Zavoj Lake!",
      gostusaName: "Gostuša Village",
      gostusaDesc: "At the foot of Stara Planina, below the vast Belan plateau, near Zavoj Lake, 25 kilometers northeast of Pirot, lies the village of Gostuša.",
      banjicaName: "Dag Banjica",
      banjicaDesc: "The Dag Banjica thermal water spring is located near Pirot in the gorge of the Gradska River. The spring is known for its constant water temperature of 28°C, and its water also has healing properties.",
      vodopadTupavica: "Tupavica Waterfall",
      vodopadTupavicaDesc: "Tupavica Waterfall is the most beautiful waterfall in Serbia. It is 15 meters high and is located on Stara Planina, near Pirot.",
      piljskiVodopad: "Piljski Waterfall",
      piljskiVodopadDesc: "With a height of 64 meters, it is the third tallest waterfall in Serbia. It is located about 4km south of the village of Topli Do, on Stara Planina.",
      cunguljskiSkok: "Čunguljski Skok",
      cunguljskiSkokDesc: "Located about 4km south of the village of Topli Do, on Stara Planina. The waterfall is 43 meters high, located at an altitude of 1400 meters.",
      kurtulskiVodopad: "Kurtulski Waterfall",
      kurtulskiVodopadDesc: "The height of the Kurtulski Skok is 27 meters. Visiting the waterfall is only allowed in the company of a mountain guide.",
      kaludjerskiSkok: "Kaluđerski Skok",
      kaludjerskiSkokDesc: "The waterfall is located on the Kaluđerska River, below Midžor, the highest peak of Stara Planina."
    },
  "latn-rs": {
    home: "Početna",
    about: "O nama",
    services: "Smeštaj i usluge",
    contact: "Kontakt",
    rights: "Sva prava zadržana.",
    hotel: "hotel",
    hotelName: "Sin-kom",
    gallery: "Galerija",
    reservationTop: "Rezervacija",
    reservation: "Rezervišite sada",
    reception: "Recepcija",
    parking: "Parking",
    wifi: "Hi-Speed Wi-Fi",
    tv: "Smart TV",
    ac: "Klima uređaj",
    conference: "Konferencija",
    conferenceMainText: "Konferencijska sala - Nudimo organizovanje predavanja, konferencija i koktela.",
    parkingMainText: "Obezbeđen besplatan parking za sve goste našeg hotela.",

    paragraph1:
      "Garni Hotel Sin-Kom počeo je sa radom 01. jula 2009. godine. Posluje na principu noćenja sa doručkom (bed&breakfast) i kategorisan je kao garni Hotel sa 3* od strane nadležnog Ministarstva Republike Srbije.",
    paragraph2:
      "Smešten je u najlepšem delu grada gde su se uz nekadašnju kaldrmu  nalazile najstarije trgovačke radnje. Danas je ovo deo grada u  kome pored starog graditeljskog jezgra dominiraju potpuno nove  moderne građevine. Na samo 200m od glavne autobuske stanice, u  pravcu koji vodi ka industrijskoj četvrti, i na 100m od skretanja  ka Parku prirode Stara Planina, Hotel Sin-Kom sagrađen je na  raskršću ovih puteva. Tako je ovaj objekat i lokacijski i  sadržajno okrenut: poslovnim ljudima, gostima u tranzitu, ali i  ljubiteljima prirode i bogatog kulturno-istorijskog nasleđa  pirotskog kraja.",
    paragraph3:
      "Garni Hotel Sin-Kom domaćin je i brojnim sportskim, kulturnim manifestacijama i takmičenjima",
    paragraph4:
      "Svaki detalj naše ponude zamišljen je tako da odgovori zahtevima modernog poslovnog sveta. Pored sopstvenog parkinga koji je pod stalnim video nadzorom, Hotel pruža mogućnost organizovanja seminara i konferencija. Sve sobe su komforne i pružaju 24-časovni pristup internetu.",
    paragraph5:
      "U skladu sa trenutnom globalnom krizom izazvanom Kovid- 19 pandemijom, poslovodstvo Hotela Sin-Kom, odlučilo je da predstojeći period učini dodatno sigurnim, čistim i bezbednim za sve naše drage Goste. Već 12 godina Hotel Sin-Kom važi za Hotel čiji je imperativ čistoća na prvom mestu. Danas, više nego ikada naša poslovna načela dolaze do izražaja. Bezbedan boravak u čistim sobama koje su sređene po najvišim hotelskim standardima i ljubazno osoblje koje poštuje sve mere zaštite danas su merilo koje gosti najviše cene.",
    paragraph6:
      "Ukoliko ste u prolazu, a želite da se odmorite  ili je Vaš poslovni put vezan za grad Pirot i okolinu, posetite nas! Pružićemo Vam idealne uslove za odmor, kvalitetnu uslugu, a ljubazno osoblje učiniće Vaš boravak prijatnim i sigurnim.",
    welcomeMessage: "Dobrodošli!",
    accomodation: "Smeštaj našeg hotela",
    requestACustomQuote: "Zatražite prilagođenu ponudu",
    conferenceRoom: "Konferencijska sala",
    location: "Lokacija",
    markText: "O nama govore naši gosti",
    servicesOfTheHotel: "Smeštaj i usluge hotela",
    servicesDescription: "Istražite smeštajne jedinice našeg hotela, kao i dodatne usluge koje nudimo.",
    conferenceText1:
      "Konferencijska Sala Hotela Sin-Kom idealna je za sve vrste seminara, prezentacija, konferencija, promocija, ili radionica.",
    conferenceText2:
      "Pregled optimalnog broja mesta (kino razmeštaj), uz mogućnost razmeštaja po Vašoj želji. Maksimalni kapacitet sale je 40 mesta.",
    serviceType: "Tip usluge",
    bedAndBreakfast: "Noćenje sa doručkom",
    roomType: "Vrsta smeštaja",
    numberOfPersons: "Broj osoba",
    onePerson: "Jedna osoba",
    twoPersons: "Dve osobe",
    options: "Opcije",
    extraBed: "Pomoćni ležaj (1900 RSD)",
    nonSmokingRoom: "Soba za nepušače",
    selectPeriod: "Izaberite period",
    addAnotherRoom: "Dodaj još jednu sobu",
    removeRoom: "Ukloni sobu",
    personalData: "Lični podaci",
    fullName: "Ime i prezime",
    mobilePhone: "Mobilni telefon",
    emailAddress: "Email adresa",
    address: "Adresa",
    city: "Grad",
    country: "Država",
    reservationNotice:
      "Slanje zahteva za rezervaciju ne podrazumeva da je Vaša rezervacija potvrđena. Naša služba recepcije će Vas obavestiti o potvrdi Vaše rezervacije putem emaila u najkraćem roku.",
    sendRequest: "Pošalji zahtev",
    roomPrice: "Cena sobe",
    clasicRoom: "Classic soba",
    clasicRoomDescription:
      "Udobna klasična soba sa svim standardnim sadržajima za prijatan boravak.",
    comfortRoom: "Comfort soba",
    comfortRoomDescription:
      "Doživite dodatnu udobnost u ovoj prostranoj sobi dizajniranoj za opuštanje.",
    doubleRoom: "Soba sa francuskim ležajem",
    doubleRoomDescription:
      "Prostrana dvokrevetna soba savršena za parove, sadrži veliki krevet i moderne pogodnosti.",
    twoBeds: "Dva standardna odvojena ležaja",
    digiSat: "Digi SAT TV",
    phoneLine: "Direktna telefonska linija",
    hairdryer: "Fen za kosu",
    sosAlarm: "SOS Alarm",
    priceOnePerson: "Noćenje sa doručkom za jednu osobu",
    priceTwoPersons: "Noćenje sa doručkom za dve osobe",
    perNight: "po noćenju",
    airConditioned: "Klimatizovano",
    doubleBed: "Francuski ležaj",
    hydromassage: "Kupatilo sa hidromasaž. kabinom",
    hydromassage2: "Hidromasaž. kabina",
    miniBar: "Mini bar",
    safe: "Sef",
    miniBarNote: "Mini bar (4 od 6 soba)",
    wirelessInternet: "Hi-Speed Wi-Fi",
    wirelessInternet2: "Hi-Speed Wi-Fi - Našim gostima obezbedili smo neograničen pristup brzom internetu.",
    pricing: "Cenovnik",
    upToHours: "Do 3 sata",
    perHour: "po satu",
    hotelGuests: "Gosti hotela",
    contactButton: "Kontaktirajte nas",
    restaurant: "Restoran",
    restaurantBreakfastInfo: "Gosti koji odsedaju u objektu Hotel Sin-Kom mogu da uživaju u visoko ocenjenom doručku tokom svog boravka. Opcije za doručak uključuju:",
    restaurantBreakfastOption1: "Na bazi samoposluživanja",
    restaurantBreakfastOption2: "À la carte (naručivanje iz jelovnika)",
    contactPageSubtitle: "Imate pitanje ili želite da rezervišete smeštaj? Slobodno nas kontaktirajte.",
    messageLabel: "Poruka",
    messagePlaceholder: "Kako vam možemo pomoći?",
    successMessage: "Vaša poruka je uspešno poslata!",
    errorMessage: "Došlo je do greške. Molimo pokušajte ponovo.",
    moreHours: "Više od 3 sata",
    priceFrom3800: "Cena od 3800 RSD",
    priceFrom5000: "Cena od 5000 RSD",
    priceFrom4000: "Cena od 4000 RSD",
    kinoKonf: "Kino postava konferencijske sale",
    konfSto: "Konferencijski sto za predavače",
    stoliceTabla: "40 stolica sa tablom",
    projektor: "Projektor",
    platno: "Projekciono platno",
    koktelKonf: "Koktel postava konferencijske sale",
    razmestajKoktel: "Mogućnost razmeštaja po Vašoj želji",
    visokiStolovi: "Postava visokih barskih stolova",
    mainPageText: "Hotel Sin-Kom — Vaš idealan smeštaj u Pirotu",
    okolinaTitle: "Otkrijte okolinu Pirota",
    zavojskoJezero: "Zavojsko Jezero",
    zavojskoDescription:
      "Na samo 15km od hotela, Zavojsko jezero je slikovito mesto idealno za šetnje i piknike u prirodi.",
    learnMore: "Saznajte više",
    staraPlaninaTitle: "Stara Planina",
    staraPlaninaDescription:
      "Stara Planina je prelepa planinska oblast idealna za pešačenje i aktivnosti na otvorenom.",
    vodopadiTitle: "Vodopadi",
    vodopadiDescription:
      "Otkrijte lepote vodopada u okolini Pirota, koje nude neverovatne pogledе i priliku za avanture u prirodi.",
    okolinaDescription:
      "Istražite prirodne lepote i atrakcije oko Pirota, od mirnih jezera do veličanstvenih planina i zadivljujućih vodopada. Bilo da tražite opuštanje ili avanturu, okolina Pirota ima nešto za svakoga.",
    reviewTitleFirst: "Desislava (Bugarska)",
    reviewDescriptionFirst:
      "Odličan odnos cene i kvaliteta. Osoblje je bilo vrlo ljubazno i uslužno. Doručak je bio vrlo dobar. Bilo je čisto, iako nameštaj nije bio nov.",
    reviewTitleSecond: "Jonas (Švedska)",
    reviewDescriptionSecond:
      "Zaista mi se svidelo ovo mesto. Vrlo lijepa soba i dobar doručak. Savršena centralna lokacija blizu autobuske stanice. Vrlo prijateljsko i uslužno osoblje.",
    reviewTitleThird: "Marina (Srbija)",
    reviewDescriptionThird:
      "U hotelu sin-kom smo boravili tri dana, lokacija hotela je super, na par minuta hoda do centra. Soba koju smo dobili je prostrana, lepa i čista jako. Krevet je udoban. Hotel je za svaku preporuku. Hvala osoblju, bilo nam je lepo, vratićemo se.",
    readReviews: "Pročitajte sve recenzije",
    surroundings: "Okolina Pirota",
    swiperLine1: "Dobrodošli u Hotel",
    swiperLine2: "u",
    swiperLine3: "Hotel",
    swiperLine4: "Sin-Kom",
    swiperLine5: "Savršeno mesto za vaš odmor",
    zanimljivostiTitle: "Zanimljivosti u Pirotu",
    zanimljivostiDescription:
      "Pirot nudi bogat kulturni sadržaj. Posetite srednjovekovnu tvrđavu Momčilov grad, istražite Muzej Ponišavlja sa autentičnom arhitekturom ili prošetajte najlepšim kejom u Srbiji pored reke Nišave.",
    kaleName: "Tvrđava Kale",
    muzejName: "Muzej Ponišavlja",
    kejName: "Keј na Nišavi",
    kaleDesc: "Tvrđava Kale je srednjovekovna tvrđava koja se nalazi u centru Pirota, poznata po svojoj istorijskoj važnosti i panoramskom pogledu na grad.",
    muzejDesc: "Muzej Ponišavlja je kulturna institucija u Pirotu koja čuva i izlaže bogatu istoriju i tradiciju regiona Ponišavlja.",
    kejDesc: "Keј na Nišavi je popularno mesto za šetnju i rekreaciju duž reke Nišave, sa prelepim pogledom.", 
    accomodationButton: "Više o smeštaju",
    jermaTitle: "Kanjon reke Jerme",
    jermaDescription:
      "Kanjon reke Jerme je spektakularna prirodna atrakcija u blizini Pirota, poznata po svojim strmim liticama i kristalno čistoj vodi, idealna za avanturiste i ljubitelje prirode.",
    poganovoName: "Manastir Poganovo",
    poganovoDesc: "Manastir Poganovo je srednjovekovni manastir smešten u kanjonu reke Jerme, poznat po svojoj arhitekturi i freskama, kao i po mirnom okruženju koje ga okružuje.",
    sukovoName: "Manastir Sukovo",
    sukovoDesc: "Manastir Sukovo je pravoslavni manastir smešten u blizini Pirota, poznat po svojoj istoriji i duhovnom značaju, kao i po prelepoj prirodi koja ga okružuje.",
    zvonackaBanjaName: "Zvončka Banja",
    zvonackaBanjaDesc: "Zvončka Banja je poznato banjsko mesto u blizini Pirota, poznato po lekovitim svojstvima svojih izvora i prelepoj prirodi koja ga okružuje.",
    selectPeriodPlaceholder: "Izaberite period boravka",
    pricingList: "Cenovnik",
    bookingBenefits: "Prednosti direktne rezervacije",
    bookingBenefit1: "- Popust od 10% za individualne rezervacije",
    bookingBenefit2: "- Rani Check-In i/ili kasniji Check-Out",
    phoneBooking: "Rezervacija telefonom",
    konfContact: "Kontaktirajte nas za personalizovanu ponudu",
    kozjiKamenName: "Kozji kamen",
    kozjiKamenDesc: "Vidikovac Kozji Kamen pruža spektakularan pogled na Zavojsko jezero i okolne planine.",
    smilovicaName: "Vidikovac Smilovica",
    smilovicaDesc: "Vidikovac Smilovica – pogled na Zavojsko jezero koji ostavlja bez daha!",
    gostusaName: "Selo Gostuša",
    gostusaDesc: "U podnožju Stare planine, ispod prostrane visoravni “Belan”, u blizini Zavojskog jezera, udaljeno 25 kilometara severoistočno od Pirota nalazi se selo Gostuša.",
    banjicaName: "Dag Banjica",
    banjicaDesc: "Izvor termalne vode Dag Banjica smešten je nedaleko od Pirota u klisuri Gradašničke reke. Izvor je poznat po konstantnoj temperaturi vode od 28 ̊C koja ima i lekovita svojstva.",
    vodopadTupavica: "Vodopad Tupavica",
    vodopadTupavicaDesc: "Vodopad Tupavica – najlepši vodopad Srbije. Visina mu je 15 metara, a nalazi se na Stara planini, nedaleko od Pirota.",
    piljskiVodopad: "Piljski vodopad",
    piljskiVodopadDesc: "Visine 64 metаrа, treći je po visini vodopаd u Srbiji. Nаlаzi se nа oko 4km južno od selа Topli Do, nа Stаroj plаnini.",
    cunguljskiSkok: "Čunguljski skok",
    cunguljskiSkokDesc: "Nаlаzi se nа Toplodolskoj reci, u blizini selа Topli Do, nа Stаroj plаnini. Vodopad je visine 43 metara,smešten na nadmorskoj visini od 1400 metara.",
    kurtulskiVodopad: "Kurtulski vodopad",
    kurtulskiVodopadDesc: "Visinа Kurtulskog skokа iznosi 27 metаrа. Obilazak vodopada isključivo u pratnji planinarskog vodiča.",
    kaludjerskiSkok: "Kaluđerski skok",
    kaludjerskiSkokDesc: "Vodopad se nalazi na Kaluđerskoj reci, ispod Midžora, najvišeg vrha Stare planine.",
  },
  "bg-bg": {
    home: "Начало",
    about: "За нас",
    services: "Услуги",
    contact: "Контакти",
    rights: "Всички права запазени.",
    hotel: "хотел",
    hotelName: "Sin-kom",
    gallery: "Галерия",
    reservation: "Резервация",
    reservationTop: "Резервация",
    reception: "Рецепция",
    parking: "Паркинг",
    wifi: "Hi-Speed Wi-Fi",
    tv: "Smart TV",
    ac: "Климатик",
    conference: "Конференция",
    paragraph1:
      "Хотел „Гарне Син-Ком“ отвори врати на 1 юли 2009 г. Той предлага настаняване със закуска и е класифициран като 3-звезден хотел „Гарне“ от съответното министерство на Република Сърбия.",
    paragraph2:
      "Той се намира в най-красивата част на града, където някога по старите калдъръмени улици са се издигали най-старите търговски магазини. Днес това е част от града, където, наред със стария архитектурен център, доминират напълно нови, модерни сгради. Само на 200 м от централната автогара, в посока към индустриалния квартал и на 100 м от отбивката за природния парк „Стара планина“, хотел „Син-Ком“ е построен на кръстопътя на тези маршрути. Поради това хотелът е насочен към бизнесмени и пътници в транзит, както и към любителите на природата и богатото културно-историческо наследство на Пиротския регион.",
    paragraph3:
      "Хотел „Гарни Син-Ком“ е домакин и на множество спортни и културни събития и състезания.",
    paragraph4:
      "Всяка подробност от нашето предложение е съобразена с изискванията на съвременния бизнес свят. Освен собствен паркинг, който се наблюдава постоянно с видеокамери, хотелът предлага възможност за организиране на семинари и конференции. Всички стаи са комфортни и разполагат с 24-часов достъп до интернет.",
    paragraph5:
      "В контекста на настоящата глобална криза, предизвикана от пандемията от COVID-19, ръководството на хотел „Син-Ком“ взе решение да направи предстоящия период изключително безопасен, чист и сигурен за всички наши скъпи гости. От 12 години хотел „Син-Ком“ е известен като място, където чистотата е наш основен приоритет. Днес, повече от всякога, нашите бизнес принципи излизат на преден план. Безопасен престой в чисти стаи, подредени според най-високите хотелиерски стандарти, и приятелски настроен персонал, който спазва всички предпазни мерки, са качествата, които нашите гости ценят най-много.",
    paragraph6:
      "Ако сте на път и искате да си починете, или ако работата ви води в Пирот и околностите, заповядайте при нас! Ние ще ви предложим идеално настаняване и висококачествено обслужване, а нашият любезен персонал ще направи престоя ви приятен и спокоен.",
    welcomeMessage: "Добре дошли!",
    accomodation: "Настаняване в нашия хотел",
    requestACustomQuote: "Поискайте индивидуална оферта",
    conferenceRoom: "Конферентна зала",
    location: "Локация",
    markText: "Какво казват нашите гости за нас",
    servicesOfTheHotel: "Хотелство и услуги на хотел",
    servicesDescription: "Разгледайте нашите хотелски помещения, както и допълнителните услуги, които предлагаме.",
    conferenceText1:
      "Конферентната зала в хотел „Син-Ком“ е идеална за провеждането на всякакви видове семинари, презентации, конференции, промоционални събития или работни срещи.",
    conferenceText2:
      "Общ преглед на оптималното разположение на седалките (разположението в кинозалата), с възможност да го подредите по ваш избор. Максималният капацитет на залата е 40 места.",
    serviceType: "Тип услуга",
    bedAndBreakfast: "Нощувка със закуска",
    roomType: "Вид настаняване",
    numberOfPersons: "Брой лица",
    onePerson: "Един човек",
    twoPersons: "Двама души",
    options: "Опции",
    extraBed: "Допълнително легло (1900 RSD)",
    nonSmokingRoom: "Стая за непушачи",
    selectPeriod: "Изберете период",
    addAnotherRoom: "Добавете още една стая",
    removeRoom: "Премахнете стаята",
    personalData: "Лични данни",
    fullName: "Име и фамилия",
    mobilePhone: "Мобилен телефон",
    emailAddress: "Имейл адрес",
    address: "Адрес",
    city: "Град",
    country: "Държава",
    reservationNotice:
      "Изпращането на заявка за резервация не означава, че вашата резервация е потвърдена. Нашата рецепция ще ви уведоми за потвърждението на вашата резервация по имейл възможно най-скоро.",
    sendRequest: "Изпрати заявка",
    roomPrice: "Цена на стаята",
    clasicRoom: "Класическа стая",
    clasicRoomDescription:
      "Удобна класическа стая с всички стандартни удобства за приятен престой.",
    comfortRoom: "Комфортна стая",
    comfortRoomDescription:
      "Насладете се на допълнителен комфорт в тази просторна стая, създадена за релакс.",
    doubleRoom: "Стая с двойно легло",
    doubleRoomDescription:
      "Просторна двойна стая, перфектна за двойки, с голямо легло и модерни удобства.",
    twoBeds: "Две стандартни отделни легла",
    digiSat: "Digi SAT TV",
    phoneLine: "Директна телефонна линия",
    hairdryer: "Сешоар",
    sosAlarm: "SOS аларма",
    priceOnePerson: "Нощувка със закуска за един човек",
    priceTwoPersons: "Нощувка със закуска за двама души",
    perNight: "на нощувка",
    airConditioned: "Климатизирано",
    doubleBed: "Двойно легло",
    hydromassage: "Баня с хидромасажна кабина",
    hydromassage2: "Хидромасажна кабина",
    miniBar: "Мини бар",
    safe: "Сейф",
    miniBarNote: "Мини бар (4 от 6 стаи)",
    wirelessInternet: "Hi-Speed Wi-Fi",
    wirelessInternet2: "Hi-Speed Wi-Fi - Предлагаме на нашите гости неограничен достъп до високоскоростен интернет.",
    conferenceMainText: "Конферентната зала - Предлагаме организиране на лекции, конференции и коктейли.",
    parkingMainText: "Осигурен безплатен паркинг за всички гости на нашия хотел.",
    pricing: "Ценообразуване",
    upToHours: "До 3 часа",
    perHour: "на час",
    hotelGuests: "Гости на хотела",
    contactButton: "Свържете се с нас",
    restaurant: "Ресторант",
    restaurantBreakfastInfo: "Гостите, отсядащи в Хотел Син-Ком, могат да се насладят на високо оценена закуска по време на престоя си. Вариантите за закуска включват:",
    restaurantBreakfastOption1: "Самообслужващ се бюфет",
    restaurantBreakfastOption2: "À la carte (поръчка от меню)",
    contactPageSubtitle: "Имате въпрос или искате да резервирате престой? Чувствайте се свободни да се свържете с нас.",
    messageLabel: "Съобщение",
    messagePlaceholder: "Как можем да ви помогнем?",
    successMessage: "Вашето съобщение беше изпратено успешно!",
    errorMessage: "Нещо се обърка. Моля, опитайте отново.",
    moreHours: "Повече от 3 часа",
    priceFrom3800: "Цена от 3800 RSD",
    priceFrom5000: "Цена от 5000 RSD",
    priceFrom4000: "Цена от 4000 RSD",
    kinoKonf: "Киносалон, организиран в конферентна зала",
    konfSto: "Конферентна маса за лектори",
    stoliceTabla: "40 стола с плот",
    projektor: "Проектор",
    platno: "Екран за прожекции",
    koktelKonf: "Коктейл в конферентната зала",
    razmestajKoktel: "Адаптивно оформление",
    visokiStolovi: "Тапициране на високи бар столове",
    mainPageText: "Хотел Син-Ком — Вашето идеално настаняване в Пирот",
    okolinaTitle: "Открийте околностите на Пирот",
    zavojskoJezero: "Завойско езеро",
    zavojskoDescription:
      "Само на 15 км от хотела, Завойско езеро е живописно място, идеално за разходки и пикници сред природата.",
    learnMore: "Научете повече",
    staraPlaninaTitle: "Стара планина",
    staraPlaninaDescription:
      "Стара планина е красива планинска област, идеална за пешеходен туризъм и дейности на открито.",
    vodopadiTitle: "Водопади",
    vodopadiDescription:
      "Открийте красивите водопади в околностите на Пирот, които предлагат невероятни гледки и възможности за приключения сред природата.",
    okolinaDescription:
      "Изследвайте природната красота и атракции около Пирот, от спокойни езера до величествени планини и зашеметяващи водопади. Независимо дали търсите релаксация или приключение, околностите на Пирот имат нещо за всеки.",
    reviewTitleFirst: "Десислава (България)",
    reviewDescriptionFirst:
      "Отлично съотношение цена-качество. Персоналът беше много любезен и отзивчив. Закуската беше много добра. Беше чисто, въпреки че мебелите не бяха нови.",
    reviewTitleSecond: "Йонас (Швеция)",
    reviewDescriptionSecond:
      "Наистина ми хареса това място. Много хубава стая и добра закуска. Перфектно централно местоположение близо до автогарата. Много приятелски и отзивчив персонал.",
    reviewTitleThird: "Марина (Сърбия)",
    reviewDescriptionThird:
      "Престояхме в хотел Син-Ком три дни, местоположението на хотела е супер, на няколко минути пеша от центъра. Стаята, която получихме, е просторна, красива и много чиста. Леглото е удобно. Хотелът е силно препоръчителен. Благодаря на персонала, имахме хубаво време, ще се върнем.",
    readReviews: "Прочетете всички отзиви",
    surroundings: "Околnosti на Пирот",
    swiperLine1: "Добре дошли в Хотел",
    swiperLine2: "в",
    swiperLine3: "Хотел",
    swiperLine4: "Син-Ком",
    swiperLine5: "Идеалното място за вашата почивка",
    zanimljivostiTitle: "Забележителности в Пирот",
    zanimljivostiDescription:
      "Пирот предлага богато културно изживяване. Посетете средновековната крепост Момчилов град, разгледайте музея Понишавля с неговата автентична архитектура или се разходете по най-красивия кей в Сърбия край река Нишава.",
    kaleName: "Кале крепост",
    muzejName: "Музей Понишавля",
    kejName: "Кей на река Нишава",
    kaleDesc: "Кале е средновековна крепост, разположена на хълм над река Нишава, предлагаща панорамни гледки към града и околностите.",
    muzejDesc: "Музей Понишавля представя богатата история и култура на региона Пирот, с експонати от древността до съвремието.",
    kejDesc: "Кей на река Нишава е популярно място за разходки и отдих, с красиви гледки към реката и възможности за водни спортове.",  
    accomodationButton: "Повече за настаняването",
    jermaTitle: "Каньонът на река Ерма",
    jermaDescription:
      "Каньонът на река Ерма е впечатляваща природна атракция в близост до Пирот, известна със своите стръмни скали и кристално чиста вода, идеална за приключенци и любители на природата.",
    poganovoName: "Манастир Поганово",
    poganovoDesc: "Манастир Поганово е средновековен манастир, разположен в каньона на река Ерма, известен със своята архитектура и фрески, както и с мирната обстановка, която го заобикаля.",
    sukovoName: "Манастир Суково",
    sukovoDesc: "Манастир Суково е православен манастир, разположен в близост до Пирот, известен със своята история и духовно значение, както и с красивата природа, която го заобикаля.",
    zvonackaBanjaName: "Звонска баня",
    zvonackaBanjaDesc: "Звонска баня е известен спа курорт в близост до Пирот, известен със своите лечебни свойства на минералните извори и красивата природа, която го заобикаля.",
    selectPeriodPlaceholder: "Изберете период на престой",  
    pricingList: "ценова листа",
    bookingBenefits: "Преимущества прямого бронирования",
    bookingBenefit1: "- 10% скидка за индивидуални бронирования",
    bookingBenefit2: "- Ранен заезд и/или късен изход",
    phoneBooking: "Брониране по телефон",
    konfContact: "Свържете се с нас за персонализирано предложение",
    kozjiKamenName: "Козък камък",
    kozjiKamenDesc: "От панорамната площадка „Козък камък“ се разкрива зашеметяваща гледка към езерото Завойско и околните планини.",
    smilovicaName: "Панорамна площадка Смиловица",
    smilovicaDesc: "Панорамната площадка Смиловица – гледка към езерото Завойско, която ще ви остави без дъх!",
    gostusaName: "Село Гостуша",
    gostusaDesc: "В подножието на Стара планина, под обширната равнина „Белан“, в близост до езерото Завойско, на 25 километра североизточно от Пирот, се намира село Гостуша.",
    banjicaName: "Даг Баня",
    banjicaDesc: "Изворът на термалната вода Даг Баня се намира недалеко от Пирот в клисурата на река Градашница. Изворът е известен с постоянната температура на водата от 28 ̊C, которая обладает лечебными свойствами.",
    vodopadTupavica: "Водопадът Тупавица",
    vodopadTupavicaDesc: "Водопадът Тупавица – най-красивият водопад в Сърбия.",
    piljskiVodopad: "Водопадът Пилски",
    piljskiVodopadDesc: "С височина от 64 метра той е третият по височина водопад в Сърбия. Намира се на около 4 км южно от село Топли До, в планината Стара.",
    cunguljskiSkok: "Скокът на жабата",
    cunguljskiSkokDesc: "Намира се на река Топлодолска, близо до село Топли До, в планината Стара. Водопадът е висок 43 метра и се намира на надморска височина от 1400 метра.",
    kurtulskiVodopad: "Водопадът Куртулски",
    kurtulskiVodopadDesc: "Visinа Kurtulskog skokа iznosi 27 metаrа. Obilazak vodopada isključivo u pratnji planinarskog vodiča.",
    kaludjerskiSkok: "Скокът на монаха",
    kaludjerskiSkokDesc: "Водопадът се намира на река Калуджерска, под Миджор – най-високия връх на Стара планина.",
  },
};

export type Language = keyof typeof translations;
